spring:
  application:
    name: haPDFy
  security:
    user:
      name: ${HAPDFY_USERNAME}
      password: ${HAPDFY_PASSWORD}
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus
