name: Check Pull Request with Maven

on:
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Run all tests
        run: mvn clean install -B -Dmaven.test.redirectTestOutputToFile=true
      - name: Publish Unit Test Results
        id: publish
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/target/surefire-reports/*.xml"
